In [3]:
import pandas as pd
import numpy as np

In [5]:
Netflix_df=pd.read_csv(r"C:\Users\hmood\Desktop\Uni\DataScience Intern\Dataset.csv")

In [6]:
Netflix_df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [7]:
Netflix_df.shape

(8790, 10)

In [8]:
Netflix_df.describe()

       release_year
count   8790.000000
mean    2014.183163
std        8.825466
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [9]:
Netflix_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8790 non-null   object
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   object
 8   duration      8790 non-null   object
 9   listed_in     8790 non-null   object
dtypes: int64(1), object(9)
memory usage: 686.8+ KB

# Data Preprocessing

## Missing Value

#### Find Miss Values Or incorrect Values (country,director)

In [20]:
 string_cols = Netflix_df.select_dtypes(include=['object']).columns
Netflix_df[string_cols] = Netflix_df[string_cols].apply(lambda col: col.str.strip())
Netflix_df.replace('', np.nan, inplace=True)

In [22]:
Netflix_df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [24]:
Netflix_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8790 non-null   object
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   object
 8   duration      8790 non-null   object
 9   listed_in     8790 non-null   object
dtypes: int64(1), object(9)
memory usage: 686.8+ KB

#### Replacing the incorrect data (not Given ) to (unknown)

In [23]:
Netflix_df['director'] = Netflix_df['director'].replace('Not Given', 'Unknown')
Netflix_df['country'] = Netflix_df['country'].replace('Not Given', 'Unknown')

In [25]:
print(Netflix_df['country'].value_counts().head(5))

country
United States     3240
India             1057
United Kingdom     638
Pakistan           421
Unknown            287
Name: count, dtype: int64

## Duplicated Row

In [28]:
print("Num of Dublicated Row:", Netflix_df.duplicated(subset=['title']).sum())
print("Num of Row:", len(Netflix_df))

Num of Dublicated Row: 4
Num of Row: 8790

In [30]:
duplicates_df = Netflix_df[Netflix_df.duplicated(subset=['title'], keep=False)].sort_values(by='title')
duplicates_df

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
393,s3997,TV Show,09-Feb,Unknown,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
537,s5965,TV Show,09-Feb,Unknown,Pakistan,3/20/2019,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
2925,s3963,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
4261,s5967,Movie,15-Aug,Swapnaneel Jayakar,India,3/29/2019,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
3285,s4523,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
4260,s5966,Movie,22-Jul,Paul Greengrass,Norway,10/10/2018,2018,R,144 min,"Dramas, Thrillers"
2590,s3372,Movie,Consequences,Ozan Açıktan,Turkey,10/25/2019,2014,TV-MA,106 min,"Dramas, International Movies, Thrillers"
4718,s6530,Movie,Consequences,Ozan Açıktan,Turkey,10/25/2019,2014,TV-MA,106 min,"Dramas, International Movies, Thrillers"

In [32]:
Netflix_df = Netflix_df.drop_duplicates(subset=['title'], keep='first')

In [34]:
print("Num of Dublicated Row:", Netflix_df.duplicated(subset=['title']).sum())
print("Num of Row:", len(Netflix_df))

Num of Dublicated Row: 0
Num of Row: 8786

## (Data Type Conversion)date_added

### convert Datatype from (object) to (datetime64) , To simplify the time analysis later.

In [38]:
Netflix_df['date_added'].head()

0    9/25/2021
1    9/24/2021
2    9/24/2021
3    9/22/2021
4    9/24/2021
Name: date_added, dtype: object

In [40]:
Netflix_df['date_added'] = pd.to_datetime(Netflix_df['date_added'], errors='coerce')

In [42]:
Netflix_df['date_added'].head()

0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-22
4   2021-09-24
Name: date_added, dtype: datetime64[ns]

## Extract Numarical Data from duration ( Moive , TV Show)

In [45]:
Netflix_df['duration_min'] = Netflix_df[Netflix_df['type'] == 'Movie']['duration'].str.extract(r'(\d+)').astype(float)
Netflix_df['seasons_count'] = Netflix_df[Netflix_df['type'] == 'TV Show']['duration'].str.extract(r'(\d+)').astype(float)

In [47]:
Netflix_df['duration_min'].head()

0     90.0
1      NaN
2      NaN
3     91.0
4    125.0
Name: duration_min, dtype: float64

In [49]:
Netflix_df['seasons_count'].head()

0    NaN
1    1.0
2    1.0
3    NaN
4    NaN
Name: seasons_count, dtype: float64

In [51]:
Netflix_df['duration_min'] = Netflix_df['duration_min'].fillna(0).astype(int)
Netflix_df['seasons_count'] = Netflix_df['seasons_count'].fillna(0).astype(int)

In [53]:
Netflix_df['duration_min'].head()

0     90
1      0
2      0
3     91
4    125
Name: duration_min, dtype: int32

##### Delete 'duration' feature to avoid duplication

In [56]:
Netflix_df.drop(columns=['duration'], inplace=True)

In [58]:
Netflix_df.head()

,show_id,type,title,director,country,date_added,release_year,rating,listed_in,duration_min,seasons_count
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,Documentaries,90,0
1,s3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",0,1
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,"TV Dramas, TV Horror, TV Mysteries",0,1
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,"Children & Family Movies, Comedies",91,0
4,s8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,"Dramas, Independent Movies, International Movies",125,0

## Extract (Year , Month ) from date_added to simplify analysis later

In [61]:
Netflix_df['year_added'] = Netflix_df['date_added'].dt.year
Netflix_df['month_added'] = Netflix_df['date_added'].dt.month_name()

In [63]:
Netflix_df['year_added'].head()

0    2021
1    2021
2    2021
3    2021
4    2021
Name: year_added, dtype: int32

In [65]:
Netflix_df['month_added'].head()

0    September
1    September
2    September
3    September
4    September
Name: month_added, dtype: object

# Save the cleaned dataset to a new CSV file

In [70]:
Netflix_df.to_csv('cleaned_netflix_dataset.csv', index=False)